name: test workflow call

on:
  workflow_call:
    inputs:
      image_type:
        required: true
        type: string

jobs:
  trigger-workflow:
    runs-on: [ self-hosted ]

    steps:
      - name: test
        run: echo "OK"
