name: test workflow call

on:
  #repository_dispatch:
  #  types: [cd_workflow_dispatch]
  workflow_call:
    inputs:
      image_type:
        required: true
        type: string

jobs:
  trigger-workflow:
    runs-on: [ self-hosted, node2 ]

    steps:
      - name: test
        run: echo ${{ inputs.image_type }}
      - name: docker ps
        run: docker ps
