# This is a basic workflow to help you get started with Actions
 
name: sf5crm-customer-sit
run-name: Deploy sf5crm-customer SIT
 
env:
  serviceName: sf5crm-customer
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch:
    # define var
    inputs:
      branch:
        description: 'select branch'
        type: string
        required: false
        default: 'sit-master'
      afcAndHil:
        description: 'Deploy AFC and HIL?'
        required: false
        type: boolean
        default: true
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # define SCM job
  pull:
    runs-on: [ node1 ]
    name: Pull Source From Github
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
  # define build job
  build:
    runs-on: [ node1 ]
    needs: [pull]
    steps:
      - name: Build Source With Maven
        run: mvn package
  # build docker image
  docker:
    runs-on: [ node1 ]
    needs: [build]
    environment: sit
    steps:
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ vars.MYNEXUSHOSTNAME }}:${{ vars.MYNEXUSHOSTEDREPOPORT }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: work space
        run: |
          echo `pwd`
      - name: Build Docker Image
        run: |
          docker build \
            --label 'biz=true' \
            --build-arg HTTP_PROXY=http://${{ secrets.PROXYUSER }}:${{ secrets.PROXYPASSWORD }}@scfcnepvip.cn.bmwgroup.net:8080 \
            --build-arg HTTPS_PROXY=http://${{ secrets.PROXYUSER }}:${{ secrets.PROXYPASSWORD }}@scfcnepvip.cn.bmwgroup.net:8080 \
            --build-arg NO_PROXY=localhost,bmwgroup.net \
            ./sf5crm-biz/biz-modules/sf5crm-customer \
            -t ${{vars.myNexusHostname}}:${{vars.myNexusHostedRepoPort}}/${{ env.serviceName }}:${{vars.envName}}_${{vars.tagName}}_${{github.run_number}}
      - name: Push Docker Image
        run: |
          docker push \
            ${{vars.myNexusHostname}}:${{vars.myNexusHostedRepoPort}}/${{ env.serviceName }}:${{vars.envName}}_${{vars.tagName}}_${{github.run_number}}
      - name: Prune Docker
        run: |
          docker system prune -af --filter "label=biz"

 
  deploy:
    needs: [ docker ]
    uses: ./.github/workflows/sit-cd-common.yml
    with:
      serviceName: 'sf5crm-customer'
      branch: 'sit-master'
    secrets: inherit
