# This is a basic workflow to help you get started with Actions
 
name: customer-sit
run-name: Deploy customer SIT
 
env:
  serviceName: customer,case
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch:
    # define var
    inputs:
      branch:
        description: 'select branch'
        type: string
        required: false
        default: 'sit-master'
      afcAndHil:
        description: 'Deploy AFC and HIL?'
        required: false
        type: boolean
        default: true
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # define SCM job
  pull:
    runs-on: [ node1 ]
    name: Pull Source From Github
    steps:
      - name: checkout
        uses: actions/checkout@v3

  # define build job
  build:
    runs-on: [ node1 ]
    needs: [pull]
    steps:
      - name: Build Source With Maven
        run: echo "build ok"
  # build docker image
  docker:
    runs-on: [ node1 ]
    needs: [build]
    outputs:
      serviceName: ${{ env.serviceName }}
    steps:
      - name: work space
        run: |
          echo `pwd`
          echo "${{ env.serviceName }}"
      
 
  deploy:
    needs: [ docker ]
    uses: ./.github/workflows/sit-cd-common.yml
    with:
      serviceName: ${{ fromJSON(needs.docker.outputs.serviceName) }}
      branch: 'sit-master'
      environment: sit
    secrets: 
      Q: ${{ secrets.Q }}
