name: YYQ Github Action Test
run-name: YYQ is learning Github Actions
jobs: 
    test: 
        runs-on: self-hosted
        steps:
            - run: echo "hello test"
            - run: echo "${{github.event_name}}"

    check-version: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4







