name: Github Action Test
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs: 
    test: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello test"
            - run: echo "${{github.event_name}}"

    check-version: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4







