name: crm-demo-nacos
run-name: crm-demo-nacos

  
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'service name'
        required: true


jobs:
  pull:
    runs-on: [ self-hosted ]
    name: Pull Source From Github
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'sit'

  deploy:
    runs-on: [ self-hosted ]
    name: rolling update deploy
    steps:
      - name: rolling update deploy
        id: rolling_update
        run: |
          echo `pwd`
          cd /root/yyq
          echo `pwd`
          ./uat-crm-rolling-update.sh ${{inputs.serviceName}}