name: crm-demo-nacos
run-name: crm-demo-nacos

  
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch

jobs:
  getNacosToken:
    runs-on: [ self-hosted ]
    name: get access token from nacos
    steps:
      - name: get access token from nacos
        id: get_nacos_token
        run: |
          echo `pwd`
          RESPONSE=$( curl -X POST 'http://101.133.164.217:8848/nacos/v1/auth/login' -d 'username=nacos&password=so-fast(Nttdata)' )
          echo "nacos_response=$RESPONSE" >> $GITHUB_OUTPUT
      - name: Parse nacos token JSON
        id: parse_nacos_token
        run: |
          echo "parse_token=${{ fromJSON(steps.get_nacos_token.outputs.nacos_response).accessToken }}" >> $GITHUB_ENV
      - name: get microservice status
        id: instance_response
        run: |
          echo "Get instance list"
          ##
          INSTANCE_LIST=$( curl -X GET "http://101.133.164.217:8848/nacos/v1/ns/instance/list?serviceName=so-fast-admin&groupName=SO_FAST_GROUP&accessToken=$parse_token")
          echo "instance list: $INSTANCE_LIST"
          echo "instance_list=$INSTANCE_LIST" >> $GITHUB_OUTPUT
      - name: Parse instance JSON
        id: parse_instance_list
        run: |
          echo "parse_instance_hosts=${{ fromJSON(steps.instance_response.outputs.instance_list).hosts }}" >> $GITHUB_OUTPUT
      - name: Offline microservice
        run: |
          echo "Offline microservice"
          ##
          echo ${{ steps.parse_instance_list.outputs.parse_instance_hosts }}
          echo "orignal: ${{ toJSON(steps.parse_instance_list.outputs.parse_instance_hosts) }}"
          echo "parse: ${hosts[@]}"
          for i in 0 1; do
            ip="${{ fromJSON(steps.parse_instance_list.outputs.parse_instance_hosts)[i].ip }}"
            echo "$ip"
          done
          #INSTANCE_LIST=$( curl -X PUT "http://101.133.164.217:8848/nacos/v1/ns/instance?accessToken=$parse_token" -d 'serviceName=nacos&password=so-fast(Nttdata))
          ##
          
      
