name: crm-demo-nacos
run-name: crm-demo-nacos

  
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch

jobs:
  getNacosToken:
    runs-on: [ self-hosted ]
    name: get access token from nacos
    steps:
      
      - name: get access token from nacos
        id: get_nacos_token
        run: |
          echo `pwd`
          RESPONSE=$( curl -X POST 'http://101.133.164.217:8848/nacos/v1/auth/login' -d 'username=nacos&password=so-fast(Nttdata)' )
          echo "::set-output name=nacos_token::${RESPONSE}"

      - name: Parse JSON
        id: parse_nacos_token
        run: |
          echo "::set-output name=parse_token::${{ fromJSON(steps.get_nacos_token.outputs.nacos_token).accessToken }}"
          echo "::set-output name=parse_ttl::${{ fromJSON(steps.get_nacos_token.outputs.nacos_token).tokenTtl }}"

      - name: get microservice status
        run: |
          echo "Access Token from Nacos: ${{steps.parse_nacos_token.outputs.parse_token}}"
          echo "Access ttl from Nacos: ${{steps.parse_nacos_token.outputs.parse_ttl}}"
          ##
          INSTANCE_LIST=$( curl -X GET http://101.133.164.217:8848/nacos/v1/ns/instance/list?serviceName=so-fast-admin&groupName=SO_FAST_GROUP&accessToken=${{steps.parse_nacos_token.outputs.parse_token}})
          ##
          echo "instance list: $INSTANCE_LIST"
      
