name: crm-demo-nacos
run-name: crm-demo-nacos

  
# Controls when the workflow will run
# define trigger event
on: 
  workflow_dispatch

jobs:
  getNacosToken:
    runs-on: [ self-hosted ]
    name: get access token from nacos
    steps:
      
      - name: get access token from nacos
        id: get_nacos_token
        run: |
          echo `pwd`
          RESPONSE=$( curl -X POST 'http://101.133.164.217:8848/nacos/v1/auth/login' -d 'username=nacos&password=so-fast(Nttdata)' )
          echo "::set-output name=nacos_token::${RESPONSE}"
          ##
          #ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.accessToken')
          #ACCESS_TOKEN=$(echo $RESPONSE | grep -oP '"accessToken"\s*:\s*"\K[^"]+')
          ## output token
          #echo "Access Token: $ACCESS_TOKEN"
          ## set env
          #echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Parse JSON
        run: |
          parsed_data="${{ fromJSON(steps.get_nacos_token.outputs.nacos_token) }}"
          echo "Value from API response: ${{ parsed_data.accessToken }}"
          echo "Value from API response: ${{ parsed_data.tokenTtl }}"

      - name: get microservice status
        run: |
          echo "Access Token from Nacos: $ACCESS_TOKEN"
          ##
          INSTANCE_LIST=$( curl -X GET http://101.133.164.217:8848/nacos/v1/ns/instance/list?serviceName=so-fast-admin&groupName=SO_FAST_GROUP&accessToken=$ACCESS_TOKEN)
          ##
          echo "instance list: $INSTANCE_LIST"
      
