# This is a basic workflow to help you get started with Actions
 
name: sit-cd-common
run-name: CD For SIT Env
 
# Controls when the workflow will run
# define trigger event
on: 
  workflow_call:
    # define var
    inputs:
      serviceName:
        description: 'Service Name'
        type: string
        required: true
        default: ''
      branch:
        description: 'Select Branch'
        type: string
        required: true
        default: ''
      afcAndHil:
        description: 'Deploy AFC and HIL?'
        required: false
        type: boolean
        default: true
      buildNo:
        description: 'Build Number'
        required: false
        type: number
        default: 0
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  # define cd job
  deploy:
    if: ${{ inputs.branch == 'sit-master' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [sf5crm-sit-hil, sf5crm-sit-afc]
    name: Deploy to SIT Server
    steps:
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ vars.MYNEXUSHOSTNAME }}:${{ vars.MYNEXUSHOSTEDREPOPORT }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Pull Docker Image
        run: docker pull ${{ myNexusHostname }}:${{ myNexusHostedRepoPort }}/${{ inputs.serviceName }}:${{vars.envName}}_${{vars.tagName}}_${{github.run_number}}
