# This is a basic workflow to help you get started with Actions
 
name: sit-cd-common
run-name: CD For SIT Env
 
# Controls when the workflow will run
# define trigger event
on: 
  workflow_call:
    secrets: 
      Q:
        required: false
    # define var
    inputs:
      serviceName:
        description: 'Service Name'
        type: string
        required: true
        default: ''
      branch:
        description: 'Select Branch'
        type: string
        required: true
        default: ''
      afcAndHil:
        description: 'Deploy AFC and HIL?'
        required: false
        type: boolean
        default: true
      buildNo:
        description: 'Build Number'
        required: false
        type: number
        default: 0
      q:
        description: 'Build Number'
        required: false
        type: string
        default: ''
      environment:
        type: string
        description: environment to deploy to
        required: true
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  # define cd job
  deploy:
    if: ${{ inputs.branch == 'sit-master' }}
    runs-on: ${{ matrix.runner }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        runner: [node2]
    name: Deploy to SIT Server
    steps:
      - name: xxxx
        env: 
          q: ${{ secrets.Q }}
        run: echo ${q}
      - name: yyyy
        run: echo "${{ fromJson(inputs.serviceName) }}"
      
